In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix,recall_score,precision_score,accuracy_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv('C:\\Users\\Admin\\OneDrive\\Desktop\\data science\\ML\\SUPERVISED LEARNING\\Dataset\\loan_approval_dataset.csv')
df

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No
...,...,...,...,...,...,...,...,...,...
995,22,49241,500,41020,24 months,Self-Employed,Owned,No,Yes
996,40,116214,423,12415,48 months,Self-Employed,Owned,No,Yes
997,27,64569,300,28155,36 months,Self-Employed,Rented,Yes,Yes
998,61,31745,490,48884,12 months,Self-Employed,Mortgage,No,Yes
999,19,46029,815,21964,24 months,Employed,Mortgage,Yes,No

In [3]:
X = df.drop(columns = 'Loan_Approved')
y = df['Loan_Approved']

In [4]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,random_state=42,train_size=0.8)

In [5]:
cat_cols = X.select_dtypes(include = 'object').columns

C:\Users\Admin\AppData\Local\Temp\ipykernel_8288\4044407438.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include = 'object').columns

In [6]:
encoder = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
encoded_values = encoder.fit_transform(xtrain[cat_cols])
columns = encoder.get_feature_names_out()
xtrain[columns] = encoded_values
xtrain.drop(columns=cat_cols,inplace=True)

In [7]:
xtrain

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
29,44,85441,507,17109,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
535,38,87298,489,10776,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
695,45,49629,762,39441,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
557,47,75337,809,40596,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
836,46,101121,504,31956,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,52,118723,689,31649,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
270,26,135654,388,22514,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
860,64,135005,683,8642,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
435,26,47856,841,45697,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
102,28,79379,306,11581,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [8]:
encoded_values_test = encoder.transform(xtest[cat_cols])
columns = encoder.get_feature_names_out()
xtest[columns] = encoded_values_test
xtest.drop(columns=cat_cols,inplace=True)

In [9]:
model = LogisticRegression(max_iter=1000)
model.fit(xtrain,ytrain)

LogisticRegression(max_iter=1000)

## **TRAIN DATA**

In [10]:
ytrain_pred = model.predict(xtrain)
print(classification_report(ytrain,ytrain_pred))

              precision    recall  f1-score   support

          No       0.54      0.51      0.53       397
         Yes       0.55      0.58      0.56       403

    accuracy                           0.55       800
   macro avg       0.54      0.54      0.54       800
weighted avg       0.54      0.55      0.54       800

**Conclusion**

* in that **predicted values** currectly predicted values as No --> 54% and falsely predicted as No -> 46%

currectly predicted as Yes --> 55% and falsely predicted as Yes -> 45% 

* in **actual values** currectly predicted as No --> 51% and falsely predicted as No -> 49%

currectly predicted as Yes --> 58% and falsely predicted as Yes -> 42%

* in the All samples currectly predicted both Yes and No as --> 55%

## **TEST DATA**

In [11]:
ytest_pred = model.predict(xtest)
print(classification_report(ytest,ytest_pred))

              precision    recall  f1-score   support

          No       0.47      0.49      0.48        95
         Yes       0.52      0.50      0.51       105

    accuracy                           0.50       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.50      0.50      0.50       200